### ISSUE TITLE
谢谢

### ISSUE THREAD

**Issue by hyyzmo** [cn2156/Acer-TMTX50-Hackintosh-OpenCore#1]
你好,感谢你提供的EFI,完美装上了mac os,现在升级到了最新的11.5.2,但是不打开啥软件发热量都很大,是因为CPU一直高频或者显存不够用吗?8G内存是不是有点不够用了🤔.

**Comment by cn2156** [comment]
8G应该够用，我只有在看视频时才发热，平时没有什么，我的是12G。
显存不是7M就是正常的，我的是1536M。

**Comment by hyyzmo** [comment]
🤔显存是1536M，可能是11.5.2有点耗资源，平时就用用safari浏览网页。我怕锁屏不能唤醒一直设置的不睡眠，只关屏幕。

**Comment by hyyzmo** [comment]
你的HDMI可以正常输出吗？我的只能通过VGA输出。🤔

**Comment by cn2156** [comment]
显存没有问题。
我也是不睡眠，屏幕也不关。
我不连外部显示器，VGA输出没有问题，但HDMI好像整个主板支持标准是1.2

**Comment by hyyzmo** [comment]
实测支持4k30hz，应该是HDMI1.4。
